# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
name: Report broken Reddit sidebar and rules URLs
author: dance2die
description: Report broken Reddit sidebar and rules URLs as GitHub issues.
inputs:
  subreddit:
    description: Subreddit name such as r/reactjs or r/javascript
    required: true
    default: r/reactjs
runs:
  # Using: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#using
  using: 'node12'
  main: index.js
# Branding: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: battery-chargin
  color: blue
