# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow
name: Report broken Subreddit sidebar and rule URLs

on:
  schedule:
    # Every week on Monday @ 00:00:00 - https://crontab.guru/#0_0_*_*_1
    - cron: '0 0 * * 1'
# on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  report_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run the node action to validate URLs and create issues
        id: report_job
        uses: r-reactjs/subreddit-rules-url-validator@master
        with:
          subreddit: r/reactjs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
