# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow
name: Report broken Subreddit sidebar and rule URLs

on: [push]

jobs:
  report_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run the node action to validate URLs and create issues
        id: report_job
        uses: r-reactjs/subreddit-rules-url-validator@hello-world-action
        with:
          subreddit: r/reactjs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
